# Generated by Django 3.1.7 on 2021-03-18 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20210318_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='cryptids',
            field=models.ManyToManyField(related_name='locations', to='polls.Cryptid'),
        ),
    ]
