# Generated by Django 3.1.7 on 2021-03-18 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20210318_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptid',
            name='photo',
            field=models.ImageField(default='err', upload_to='media/upload'),
        ),
    ]
