# Generated by Django 3.1.7 on 2021-03-18 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_cryptid_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptid',
            name='photo',
            field=models.ImageField(default='err', upload_to='media/media/upload'),
        ),
    ]
