# Generated by Django 3.1.7 on 2021-03-18 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20210318_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptid',
            name='photo',
            field=models.ImageField(default='err', upload_to='media/upload'),
        ),
    ]
