# Generated by Django 3.1.7 on 2021-03-19 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20210318_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptid',
            name='photo',
            field=models.ImageField(default='None', upload_to='media/upload'),
        ),
    ]
